defaults.url=https://sentry.io/
# Optionally set your organization and project here, else specify via CLI args
# defaults.org=your-org-slug
# defaults.project=your-project-slug

# Read token from environment
auth.token=${SENTRY_AUTH_TOKEN}

# Do not commit real tokens to source control. Ensure .env.local is in .gitignore
